use std::collections::{BTreeSet, HashMap};
use std::fs;
use std::os::unix::fs::{PermissionsExt, symlink};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};
use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, Ordering};

use anyhow::{Context, Result, bail};
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};
use rayon::prelude::*;

use crate::config::{Config, LinkSpec, ResolvedVirtualEnv};
use crate::locator::Locator;
use crate::state::{ManagedState, VenvState};

const SENTINEL: &str = "# Auto-generated by venvs";

/// Run the converge process: remove orphans, then create/update all
/// configured virtualenvs (in parallel).
pub fn run(
    locator: &Locator,
    link_dir: &Path,
    fail_fast: bool,
    names: &[String],
) -> Result<ExitCode> {
    let uv = find_uv()?;
    let config = Config::from_file(&locator.config_path())?;
    let state_path = locator.root.join("managed.json");
    let mut state = ManagedState::load(&state_path)?;

    let current_names: BTreeSet<String> = config.virtualenvs.keys().cloned().collect();

    // Phase 1: Remove orphans (fast, serial).
    remove_orphans(&mut state, &current_names, locator)?;

    // Pre-resolve python versions (avoid redundant subprocess calls).
    let python_versions = resolve_python_versions(&uv, &config)?;

    // Phase 2: Converge each configured virtualenv in parallel.
    let venvs_to_process: Vec<_> = if names.is_empty() {
        config.virtualenvs.values().collect()
    } else {
        let filter: BTreeSet<&str> = names.iter().map(String::as_str).collect();
        config
            .virtualenvs
            .values()
            .filter(|v| filter.contains(v.name.as_str()))
            .collect()
    };

    let state = Mutex::new(state);
    let cancelled = AtomicBool::new(false);

    let multi_progress = MultiProgress::new();
    let style = ProgressStyle::with_template("{spinner:.green} [{elapsed_precise}] {msg}").unwrap();

    let errors: Vec<_> = venvs_to_process
        .par_iter()
        .filter_map(|resolved| {
            if fail_fast && cancelled.load(Ordering::Relaxed) {
                return None;
            }

            let pb = multi_progress.add(ProgressBar::new_spinner());
            pb.set_style(style.clone());
            pb.set_message(resolved.name.clone());
            pb.enable_steady_tick(std::time::Duration::from_millis(100));

            let sys_version = python_versions.get(&resolved.python).unwrap();
            let result = converge_one(&uv, resolved, locator, link_dir, &state, sys_version, &pb);

            match &result {
                Ok(()) => {
                    pb.finish_with_message(format!("{} \u{2714}", resolved.name,));
                }
                Err(e) => {
                    if fail_fast {
                        cancelled.store(true, Ordering::Relaxed);
                    }
                    pb.finish_with_message(format!("{} FAILED: {e:#}", resolved.name,));
                }
            }

            result.err().map(|e| (resolved.name.clone(), e))
        })
        .collect();

    // Save state (even on partial failure, so successful venvs are tracked).
    let state = state.into_inner().unwrap();
    state.save(&state_path).context("saving managed state")?;

    if errors.is_empty() {
        return Ok(ExitCode::SUCCESS);
    }

    eprintln!();
    for (name, err) in &errors {
        eprintln!("Converging {name:?} failed: {err:#}");
    }
    if fail_fast {
        bail!("{} virtualenv(s) failed to converge", errors.len());
    }
    Ok(ExitCode::FAILURE)
}

fn find_uv() -> Result<PathBuf> {
    which::which("uv").context("venvs requires uv to be installed and on PATH")
}

/// Resolve all distinct python specs to their version strings up front,
/// so parallel workers don't each shell out for the same interpreter.
fn resolve_python_versions(uv: &Path, config: &Config) -> Result<HashMap<String, String>> {
    let specs: BTreeSet<&str> = config
        .virtualenvs
        .values()
        .map(|v| v.python.as_str())
        .collect();

    let mut versions = HashMap::with_capacity(specs.len());
    for spec in specs {
        let version = get_python_version(uv, spec)?;
        versions.insert(spec.to_string(), version);
    }
    Ok(versions)
}

fn get_python_version(uv: &Path, python: &str) -> Result<String> {
    let output = Command::new(uv)
        .args(["python", "find", python])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .context("finding python interpreter via uv")?;

    if !output.status.success() {
        bail!(
            "could not find python interpreter {python:?}: {}",
            String::from_utf8_lossy(&output.stderr).trim(),
        );
    }

    let python_path = String::from_utf8(output.stdout)
        .context("uv python find returned non-UTF-8")?
        .trim()
        .to_string();

    let output = Command::new(&python_path)
        .arg("--version")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .with_context(|| format!("running {python_path} --version"))?;

    String::from_utf8(output.stdout)
        .context("python --version returned non-UTF-8")
        .map(|s| s.trim().to_string())
}

// -- Orphan removal --

fn remove_orphans(
    state: &mut ManagedState,
    current_names: &BTreeSet<String>,
    locator: &Locator,
) -> Result<()> {
    let orphan_names = state.orphaned_names(current_names);

    for name in &orphan_names {
        eprintln!("Removing orphaned virtualenv: {name}");

        if let Some(venv_state) = state.venvs.get(name) {
            remove_links(&venv_state.links);
        }

        let venv_dir = locator.for_name(name);
        if venv_dir.exists() {
            fs::remove_dir_all(&venv_dir)
                .with_context(|| format!("removing orphaned venv {}", venv_dir.display()))?;
        }

        state.venvs.remove(name);
    }

    Ok(())
}

fn remove_links(links: &[PathBuf]) {
    for path in links {
        // symlink_metadata succeeds for broken symlinks (unlike exists()).
        if path.symlink_metadata().is_ok() {
            let _ = fs::remove_file(path);
        }
    }
}

// -- Per-venv convergence --

fn converge_one(
    uv: &Path,
    resolved: &ResolvedVirtualEnv,
    locator: &Locator,
    link_dir: &Path,
    state: &Mutex<ManagedState>,
    sys_version: &str,
    pb: &ProgressBar,
) -> Result<()> {
    let venv_dir = locator.for_name(&resolved.name);

    // Snapshot what we need from state in a single short lock.
    let (needs_update, old_links) = {
        let state = state.lock().unwrap();
        let needs_update = state.needs_update(&resolved.name, resolved, sys_version);
        let old_links = state.venvs.get(&resolved.name).map(|v| v.links.clone());
        (needs_update, old_links)
    };

    // Health check runs outside the lock (it spawns a subprocess).
    if !needs_update && health_check(&venv_dir) {
        return Ok(());
    }

    // Clean up stale links from the previous convergence of this venv.
    if let Some(links) = &old_links {
        remove_links(links);
    }

    // Recreate the venv.
    pb.set_message(format!("{}: creating venv", resolved.name));
    if venv_dir.exists() {
        fs::remove_dir_all(&venv_dir)
            .with_context(|| format!("removing existing venv {}", venv_dir.display()))?;
    }

    run_captured(
        Command::new(uv)
            .args(["venv", "--python", &resolved.python, "--quiet"])
            .arg(&venv_dir),
        &resolved.name,
        "uv venv",
    )?;

    // Install packages.
    if !resolved.install.is_empty() || !resolved.requirements.is_empty() {
        pb.set_message(format!("{}: installing packages", resolved.name));

        let venv_python = venv_dir.join("bin/python");
        let mut cmd = Command::new(uv);
        cmd.args(["pip", "install", "--python"])
            .arg(&venv_python)
            .arg("--quiet");
        for package in &resolved.install {
            cmd.arg(package);
        }
        for req in &resolved.requirements {
            cmd.args(["-r", req.as_str()]);
        }
        run_captured(&mut cmd, &resolved.name, "uv pip install")?;
    }

    // Create links.
    pb.set_message(format!("{}: linking", resolved.name));
    fs::create_dir_all(link_dir)
        .with_context(|| format!("creating link directory {}", link_dir.display()))?;

    let mut created_links = Vec::with_capacity(resolved.link.len() + resolved.link_module.len());

    for link in &resolved.link {
        created_links.push(create_symlink(&venv_dir, link, link_dir)?);
    }
    for link in &resolved.link_module {
        created_links.push(write_module_wrapper(&venv_dir, link, link_dir)?);
    }

    // Update state (before post-commands, so links are tracked even if
    // a post-command fails).
    {
        let mut state = state.lock().unwrap();
        state.venvs.insert(
            resolved.name.clone(),
            VenvState {
                config: resolved.clone(),
                sys_version: sys_version.to_string(),
                links: created_links,
            },
        );
    }

    // Run post-commands.
    for command in &resolved.post_commands {
        if command.is_empty() {
            continue;
        }
        pb.set_message(format!("{}: running {}", resolved.name, command[0],));
        let status = Command::new(&command[0])
            .args(&command[1..])
            .status()
            .with_context(|| format!("running post-command: {command:?}"))?;
        if !status.success() {
            bail!("post-command failed for {}: {command:?}", resolved.name,);
        }
    }

    Ok(())
}

/// Run a command, capturing stdout/stderr. On failure, include stderr
/// in the error message (so it doesn't interleave with progress bars
/// during normal operation).
fn run_captured(cmd: &mut Command, venv_name: &str, description: &str) -> Result<()> {
    let output = cmd
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .with_context(|| format!("running {description}"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("{description} failed for {venv_name}:\n{stderr}");
    }
    Ok(())
}

/// Check that a venv's python interpreter actually works.
fn health_check(venv_dir: &Path) -> bool {
    let python = venv_dir.join("bin/python");
    Command::new(&python)
        .args(["-c", ""])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn create_symlink(venv_dir: &Path, link: &LinkSpec, link_dir: &Path) -> Result<PathBuf> {
    let source = venv_dir.join("bin").join(&link.source);
    let target = link_dir.join(&link.target);

    if let Ok(meta) = target.symlink_metadata() {
        if meta.file_type().is_symlink() {
            if fs::read_link(&target).ok().as_ref() == Some(&source) {
                return Ok(target);
            }
            // Broken symlink or points elsewhere — only replace if broken.
            if target.exists() {
                bail!(
                    "link target {} already exists \
                     (symlink to something else)",
                    target.display(),
                );
            }
            fs::remove_file(&target)?;
        } else {
            bail!(
                "link target {} already exists (not a symlink)",
                target.display(),
            );
        }
    }

    symlink(&source, &target)
        .with_context(|| format!("symlinking {} -> {}", source.display(), target.display(),))?;

    Ok(target)
}

fn write_module_wrapper(venv_dir: &Path, link: &LinkSpec, link_dir: &Path) -> Result<PathBuf> {
    let python = venv_dir.join("bin/python");
    let target = link_dir.join(&link.target);

    // Refuse to overwrite files we didn't generate.
    if target.exists() {
        let contents = fs::read_to_string(&target).unwrap_or_default();
        let mut lines = contents.lines();
        lines.next(); // skip shebang
        if !lines.next().is_some_and(|l| l.starts_with(SENTINEL)) {
            bail!(
                "link target {} already exists (not a venvs wrapper)",
                target.display(),
            );
        }
    }

    let wrapper = format!(
        "\
#!{python}
{SENTINEL}
# Don't modify this file, it may be replaced when re-converging.
import os
import sys
# No runpy.run_module because of https://bugs.python.org/issue37941 ...
argv = [sys.executable, \"-m\", \"{module}\"] + sys.argv[1:]
os.execvp(argv[0], argv)
",
        python = python.display(),
        module = link.source,
    );

    fs::write(&target, &wrapper)
        .with_context(|| format!("writing module wrapper {}", target.display()))?;

    let mut perms = fs::metadata(&target)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&target, perms)?;

    Ok(target)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn health_check_nonexistent_dir() {
        assert!(!health_check(Path::new("/nonexistent/venv")));
    }

    #[test]
    fn create_symlink_new() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        let result = create_symlink(&venv_dir, &spec, &link_dir).unwrap();
        assert_eq!(result, link_dir.join("mytool"));
        assert_eq!(
            fs::read_link(link_dir.join("mytool")).unwrap(),
            bin_dir.join("mytool"),
        );
    }

    #[test]
    fn create_symlink_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        create_symlink(&venv_dir, &spec, &link_dir).unwrap();
        // Second call should succeed (same target).
        create_symlink(&venv_dir, &spec, &link_dir).unwrap();
    }

    #[test]
    fn create_symlink_replaces_broken() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        // Create a broken symlink.
        symlink("/nonexistent/target", link_dir.join("mytool")).unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        create_symlink(&venv_dir, &spec, &link_dir).unwrap();
        assert_eq!(
            fs::read_link(link_dir.join("mytool")).unwrap(),
            bin_dir.join("mytool"),
        );
    }

    #[test]
    fn create_symlink_refuses_existing_file() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        // Create a real file at the target.
        fs::write(link_dir.join("mytool"), "something").unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        assert!(create_symlink(&venv_dir, &spec, &link_dir).is_err());
    }

    #[test]
    fn create_symlink_refuses_existing_symlink_to_other_target() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        // Create a working symlink to a different file.
        let other_file = dir.path().join("other");
        fs::write(&other_file, "other").unwrap();
        symlink(&other_file, link_dir.join("mytool")).unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        assert!(create_symlink(&venv_dir, &spec, &link_dir).is_err());
    }

    #[test]
    fn write_module_wrapper_creates_executable() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        let spec = LinkSpec {
            source: "mymodule".into(),
            target: "mymod".into(),
        };

        let result = write_module_wrapper(&venv_dir, &spec, &link_dir).unwrap();
        assert_eq!(result, link_dir.join("mymod"));

        let contents = fs::read_to_string(&result).unwrap();
        assert!(contents.starts_with("#!"));
        assert!(contents.contains(SENTINEL));
        assert!(contents.contains("\"mymodule\""));

        let mode = fs::metadata(&result).unwrap().permissions().mode();
        assert_ne!(mode & 0o111, 0, "wrapper should be executable");
    }

    #[test]
    fn write_module_wrapper_replaces_own_wrappers() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        let spec = LinkSpec {
            source: "mymodule".into(),
            target: "mymod".into(),
        };

        write_module_wrapper(&venv_dir, &spec, &link_dir).unwrap();
        // Second call should succeed (replaces its own wrapper).
        write_module_wrapper(&venv_dir, &spec, &link_dir).unwrap();
    }

    #[test]
    fn write_module_wrapper_refuses_foreign_files() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        // Create a file that isn't a venvs wrapper.
        fs::write(link_dir.join("mymod"), "something else\n").unwrap();

        let spec = LinkSpec {
            source: "mymodule".into(),
            target: "mymod".into(),
        };

        assert!(write_module_wrapper(&venv_dir, &spec, &link_dir).is_err());
    }
}
