use std::collections::{BTreeSet, HashMap};
use std::fs::{self, File, TryLockError};
use std::io::{self, Write};
use std::os::unix::fs::{PermissionsExt, symlink};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};
use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, Ordering};

use anyhow::{Context, Result, bail};
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};
use rayon::prelude::*;

use crate::config::{Config, LinkSpec, ResolvedVirtualEnv};
use crate::locator::Locator;
use crate::state::{ManagedState, VenvState};

const SENTINEL: &str = "# Auto-generated by venvs";

// -- Plan --

/// One step the run is going to take. The plan is built from config + state
/// snapshot in a single place; downstream strategies (Apply, DryRun) are
/// pure consumers that don't re-derive any decisions.
#[derive(Debug)]
struct Plan {
    orphans: Vec<Orphan>,
    items: Vec<Item>,
    /// Whether the link dir already exists at planning time. Captured here
    /// so `print_plan` doesn't reach back into the filesystem.
    link_dir_exists: bool,
}

impl Plan {
    /// Whether the plan would actually change anything (orphan removals or
    /// any non-skip item).
    fn has_changes(&self) -> bool {
        !self.orphans.is_empty()
            || self
                .items
                .iter()
                .any(|item| !matches!(item.verdict, Verdict::Skip))
    }
}

#[derive(Debug)]
struct Orphan {
    name: String,
    links: Vec<PathBuf>,
}

#[derive(Debug)]
struct Item {
    resolved: ResolvedVirtualEnv,
    sys_version: String,
    verdict: Verdict,
}

#[derive(Debug)]
enum Verdict {
    Skip,
    Create,
    Update {
        reasons: Vec<String>,
        old_links: Vec<PathBuf>,
    },
}

fn build_plan(
    config: &Config,
    state: &ManagedState,
    sys_versions: &HashMap<String, String>,
    names: &[String],
    locator: &Locator,
    link_dir: &Path,
) -> Result<Plan> {
    let unknown: Vec<&str> = names
        .iter()
        .filter(|n| !config.virtualenvs.contains_key(n.as_str()))
        .map(String::as_str)
        .collect();
    if !unknown.is_empty() {
        bail!("unknown virtualenv name(s): {}", unknown.join(", "));
    }

    let current: BTreeSet<String> = config.virtualenvs.keys().cloned().collect();
    let orphans: Vec<Orphan> = state
        .orphaned_names(&current)
        .into_iter()
        .map(|name| {
            let links = state
                .venvs
                .get(&name)
                .map(|v| v.links.clone())
                .unwrap_or_default();
            Orphan { name, links }
        })
        .collect();

    let venvs_to_process: Vec<&ResolvedVirtualEnv> = if names.is_empty() {
        config.virtualenvs.values().collect()
    } else {
        let filter: BTreeSet<&str> = names.iter().map(String::as_str).collect();
        config
            .virtualenvs
            .values()
            .filter(|v| filter.contains(v.name.as_str()))
            .collect()
    };

    let items = venvs_to_process
        .into_iter()
        .map(|resolved| {
            let sys_version = sys_versions
                .get(&resolved.python)
                .cloned()
                .expect("python version must be resolved before planning");
            let venv_dir = locator.for_name(&resolved.name);
            let verdict = match state.venvs.get(&resolved.name) {
                None => Verdict::Create,
                Some(existing) => {
                    let healthy = health_check(&venv_dir);
                    let mut reasons = describe_changes(existing, resolved, &sys_version);
                    if reasons.is_empty() && healthy {
                        Verdict::Skip
                    } else {
                        if reasons.is_empty() && !healthy {
                            reasons.push("venv missing or broken".to_string());
                        }
                        Verdict::Update {
                            reasons,
                            old_links: existing.links.clone(),
                        }
                    }
                }
            };
            Item {
                resolved: resolved.clone(),
                sys_version,
                verdict,
            }
        })
        .collect();

    Ok(Plan {
        orphans,
        items,
        link_dir_exists: link_dir.exists(),
    })
}

/// List the specific reasons an existing venv differs from its desired
/// configuration. Empty means no config-level change (a recreation might
/// still be triggered by a broken venv on disk).
fn describe_changes(
    existing: &VenvState,
    resolved: &ResolvedVirtualEnv,
    sys_version: &str,
) -> Vec<String> {
    let mut reasons = Vec::new();
    if existing.sys_version != sys_version {
        reasons.push(format!(
            "python version: {} -> {}",
            existing.sys_version, sys_version,
        ));
    }
    if existing.config.python != resolved.python {
        reasons.push(format!(
            "python spec: {} -> {}",
            existing.config.python, resolved.python,
        ));
    }
    if existing.config.install != resolved.install {
        reasons.push(diff_strings(
            "install",
            &existing.config.install,
            &resolved.install,
        ));
    }
    if existing.config.requirements != resolved.requirements {
        reasons.push(diff_strings(
            "requirements",
            &existing.config.requirements,
            &resolved.requirements,
        ));
    }
    if existing.config.link != resolved.link {
        reasons.push(diff_links("links", &existing.config.link, &resolved.link));
    }
    if existing.config.link_module != resolved.link_module {
        reasons.push(diff_links(
            "link-modules",
            &existing.config.link_module,
            &resolved.link_module,
        ));
    }
    if existing.config.post_commands != resolved.post_commands {
        reasons.push("post-commands changed".to_string());
    }
    reasons
}

/// Format a multiset diff between two ordered string lists as
/// `label: +added -removed`. If the multisets are equal but the order
/// differs, reports `<label> reordered`. Operates on multisets (counts
/// matter) so a duplicated entry being removed shows as `-foo`, not as
/// a misleading "reordered".
fn diff_strings(label: &str, old: &[String], new: &[String]) -> String {
    let old_counts = count_by(old);
    let new_counts = count_by(new);
    let mut added = Vec::new();
    let mut removed = Vec::new();
    let keys: BTreeSet<&str> = old_counts
        .keys()
        .chain(new_counts.keys())
        .copied()
        .collect();
    for key in keys {
        let o = old_counts.get(key).copied().unwrap_or(0);
        let n = new_counts.get(key).copied().unwrap_or(0);
        for _ in 0..n.saturating_sub(o) {
            added.push(key);
        }
        for _ in 0..o.saturating_sub(n) {
            removed.push(key);
        }
    }
    if added.is_empty() && removed.is_empty() {
        return format!("{label} reordered");
    }
    let mut parts = Vec::with_capacity(added.len() + removed.len());
    parts.extend(added.iter().map(|p| format!("+{p}")));
    parts.extend(removed.iter().map(|p| format!("-{p}")));
    format!("{label}: {}", parts.join(" "))
}

fn count_by(items: &[String]) -> HashMap<&str, usize> {
    let mut counts: HashMap<&str, usize> = HashMap::new();
    for item in items {
        *counts.entry(item.as_str()).or_insert(0) += 1;
    }
    counts
}

fn diff_links(label: &str, old: &[LinkSpec], new: &[LinkSpec]) -> String {
    let format_spec = |s: &LinkSpec| {
        if s.source == s.target {
            s.source.clone()
        } else {
            format!("{}:{}", s.source, s.target)
        }
    };
    let old_strings: Vec<String> = old.iter().map(format_spec).collect();
    let new_strings: Vec<String> = new.iter().map(format_spec).collect();
    diff_strings(label, &old_strings, &new_strings)
}

// -- Strategy --

/// What to do with the planned actions.
///
/// `Apply` performs them; `DryRun` prints them. The boolean that previously
/// would have threaded through `run()` and `converge_one()` is replaced by
/// picking which `Strategy` to instantiate at the entry point.
pub trait Strategy {
    fn run(self, locator: &Locator, link_dir: &Path, names: &[String]) -> Result<ExitCode>;
}

pub struct Apply {
    pub fail_fast: bool,
}

pub struct DryRun;

impl Strategy for Apply {
    fn run(self, locator: &Locator, link_dir: &Path, names: &[String]) -> Result<ExitCode> {
        // Lock before Prep::load: shelling out to `uv python find` for every
        // configured spec is wasted work if we're going to block on the lock
        // anyway. Prep::load reads the config file and uv subprocesses, none
        // of which need to happen until we own the right to mutate state.
        let _lock = acquire_lock(&locator.root)?;
        let prep = Prep::load(locator)?;
        let state = ManagedState::load(&prep.state_path)?;
        let plan = build_plan(
            &prep.config,
            &state,
            &prep.python_versions,
            names,
            locator,
            link_dir,
        )?;
        apply(
            plan,
            state,
            &prep.state_path,
            &prep.uv,
            locator,
            link_dir,
            self.fail_fast,
        )
    }
}

impl Strategy for DryRun {
    fn run(self, locator: &Locator, link_dir: &Path, names: &[String]) -> Result<ExitCode> {
        let prep = Prep::load(locator)?;
        let state = ManagedState::load(&prep.state_path)?;
        let plan = build_plan(
            &prep.config,
            &state,
            &prep.python_versions,
            names,
            locator,
            link_dir,
        )?;
        let mut stdout = io::stdout().lock();
        print_plan(&plan, link_dir, &mut stdout)?;
        Ok(ExitCode::from(dry_run_exit_code(&plan)))
    }
}

/// Mirror terraform/diff conventions: 0 = no changes, 2 = changes pending,
/// anything non-zero from `?` propagation = error. Lets CI gate on "is
/// anything drifted" without parsing stdout.
fn dry_run_exit_code(plan: &Plan) -> u8 {
    if plan.has_changes() { 2 } else { 0 }
}

/// Shared per-run setup that doesn't depend on the strategy: locate uv,
/// load config, resolve python versions.
struct Prep {
    uv: PathBuf,
    config: Config,
    state_path: PathBuf,
    python_versions: HashMap<String, String>,
}

impl Prep {
    fn load(locator: &Locator) -> Result<Self> {
        let uv = find_uv()?;
        let config = Config::from_file(&locator.config_path())?;
        let state_path = locator.root.join("managed.json");
        let python_versions = resolve_python_versions(&uv, &config)?;
        Ok(Self {
            uv,
            config,
            state_path,
            python_versions,
        })
    }
}

// -- Apply: execute the plan --

fn apply(
    plan: Plan,
    mut state: ManagedState,
    state_path: &Path,
    uv: &Path,
    locator: &Locator,
    link_dir: &Path,
    fail_fast: bool,
) -> Result<ExitCode> {
    // Phase 1: orphans (serial, persist before continuing so an interrupted
    // run doesn't try to re-remove them on the next pass).
    for orphan in &plan.orphans {
        eprintln!("Removing orphaned virtualenv: {}", orphan.name);
        remove_links(&orphan.links, &locator.root);
        let venv_dir = locator.for_name(&orphan.name);
        if venv_dir.exists() {
            fs::remove_dir_all(&venv_dir)
                .with_context(|| format!("removing orphaned venv {}", venv_dir.display()))?;
        }
        state.venvs.remove(&orphan.name);
    }
    state
        .save(state_path)
        .context("saving managed state after orphan removal")?;

    // Announce per-venv intentions before progress bars start, so the user
    // can see *why* something is being recreated (not just that it is).
    for item in &plan.items {
        match &item.verdict {
            Verdict::Skip => {}
            Verdict::Create => eprintln!("Creating {}", item.resolved.name),
            Verdict::Update { reasons, .. } => {
                eprintln!("Updating {}: {}", item.resolved.name, reasons.join("; "));
            }
        }
    }

    // Phase 2: create/update in parallel.
    fs::create_dir_all(link_dir)
        .with_context(|| format!("creating link directory {}", link_dir.display()))?;

    let state = Mutex::new(state);
    let cancelled = AtomicBool::new(false);
    let multi = MultiProgress::new();
    let style = ProgressStyle::with_template("{spinner:.green} [{elapsed_precise}] {msg}").unwrap();

    let errors: Vec<_> = plan
        .items
        .par_iter()
        .filter_map(|item| {
            if fail_fast && cancelled.load(Ordering::Relaxed) {
                return None;
            }

            let pb = multi.add(ProgressBar::new_spinner());
            pb.set_style(style.clone());
            pb.set_message(item.resolved.name.clone());
            pb.enable_steady_tick(std::time::Duration::from_millis(100));

            let ui = Ui {
                pb: &pb,
                multi: &multi,
            };
            let result = match &item.verdict {
                Verdict::Skip => Ok(()),
                Verdict::Create => converge_one(
                    uv,
                    &item.resolved,
                    locator,
                    link_dir,
                    &state,
                    state_path,
                    &item.sys_version,
                    &[],
                    &ui,
                ),
                Verdict::Update { old_links, .. } => converge_one(
                    uv,
                    &item.resolved,
                    locator,
                    link_dir,
                    &state,
                    state_path,
                    &item.sys_version,
                    old_links,
                    &ui,
                ),
            };

            let name = &item.resolved.name;
            match result {
                Ok(()) => {
                    pb.finish_with_message(format!("{name} \u{2714}"));
                    None
                }
                Err(e) => {
                    if fail_fast {
                        cancelled.store(true, Ordering::Relaxed);
                    }
                    pb.finish_with_message(format!("{name} FAILED: {e:#}"));
                    Some((name.clone(), e))
                }
            }
        })
        .collect();

    let state = state.into_inner().unwrap_or_else(|p| p.into_inner());
    state.save(state_path).context("saving managed state")?;

    if errors.is_empty() {
        return Ok(ExitCode::SUCCESS);
    }

    eprintln!();
    for (name, err) in &errors {
        eprintln!("Converging {name:?} failed: {err:#}");
    }
    if fail_fast {
        bail!("{} virtualenv(s) failed to converge", errors.len());
    }
    Ok(ExitCode::FAILURE)
}

// -- DryRun: print the plan --

/// Render the plan to `out`. Skip items are intentionally not shown:
/// dry-run is a diff, and dragging in N up-to-date venvs alongside one
/// pending change buries the signal. (A future `--verbose` could surface
/// them on demand.)
fn print_plan(plan: &Plan, link_dir: &Path, out: &mut impl Write) -> io::Result<()> {
    if !plan.has_changes() {
        writeln!(out, "Already up to date — no changes needed.")?;
        return Ok(());
    }

    for orphan in &plan.orphans {
        writeln!(
            out,
            "Would remove orphan: {} ({} link(s))",
            orphan.name,
            orphan.links.len(),
        )?;
    }
    if !plan.link_dir_exists {
        writeln!(out, "Would create link directory: {}", link_dir.display())?;
    }
    for item in &plan.items {
        let name = &item.resolved.name;
        match &item.verdict {
            Verdict::Skip => continue,
            Verdict::Create => writeln!(
                out,
                "Would create: {name} (python: {}, install: {}, links: {})",
                item.resolved.python,
                item.resolved.install.len(),
                item.resolved.link.len() + item.resolved.link_module.len(),
            )?,
            Verdict::Update { reasons, .. } => {
                writeln!(out, "Would update: {name} ({})", reasons.join("; "))?;
            }
        }
    }
    Ok(())
}

// -- Setup --

fn find_uv() -> Result<PathBuf> {
    which::which("uv").context("venvs requires uv to be installed and on PATH")
}

/// Acquire an exclusive lock on the venvs root so concurrent `converge`
/// invocations can't corrupt shared state. Returns the locked File; when
/// it's dropped the lock releases automatically.
fn acquire_lock(root: &Path) -> Result<File> {
    fs::create_dir_all(root).with_context(|| format!("creating venvs root {}", root.display()))?;
    let lock_path = root.join(".lock");
    let file = File::options()
        .create(true)
        .truncate(false)
        .write(true)
        .open(&lock_path)
        .with_context(|| format!("opening lock file {}", lock_path.display()))?;
    match file.try_lock() {
        Ok(()) => Ok(file),
        Err(TryLockError::WouldBlock) => {
            bail!(
                "another venvs converge is running (lock held on {})",
                lock_path.display(),
            )
        }
        Err(TryLockError::Error(e)) => {
            Err(e).with_context(|| format!("locking {}", lock_path.display()))
        }
    }
}

/// Resolve all distinct python specs to their version strings up front,
/// so parallel workers don't each shell out for the same interpreter.
fn resolve_python_versions(uv: &Path, config: &Config) -> Result<HashMap<String, String>> {
    let specs: BTreeSet<&str> = config
        .virtualenvs
        .values()
        .map(|v| v.python.as_str())
        .collect();

    specs
        .par_iter()
        .map(|spec| Ok((spec.to_string(), get_python_version(uv, spec)?)))
        .collect()
}

fn get_python_version(uv: &Path, python: &str) -> Result<String> {
    let output = Command::new(uv)
        .args(["python", "find", python])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .context("finding python interpreter via uv")?;

    if !output.status.success() {
        bail!(
            "could not find python interpreter {python:?}: {}",
            String::from_utf8_lossy(&output.stderr).trim(),
        );
    }

    let python_path = String::from_utf8(output.stdout)
        .context("uv python find returned non-UTF-8")?
        .trim()
        .to_string();

    let output = Command::new(&python_path)
        .arg("--version")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .with_context(|| format!("running {python_path} --version"))?;

    if !output.status.success() {
        bail!(
            "{python_path} --version failed: {}",
            String::from_utf8_lossy(&output.stderr).trim(),
        );
    }

    String::from_utf8(output.stdout)
        .context("python --version returned non-UTF-8")
        .map(|s| s.trim().to_string())
}

/// Remove paths recorded as belonging to a venv, but only if they still
/// look like ours: a symlink whose target lives under `venv_root`, or a
/// regular file carrying our wrapper sentinel. A tampered or stale state
/// file with arbitrary paths in `links` therefore can't trick us into
/// deleting unrelated files.
fn remove_links(links: &[PathBuf], venv_root: &Path) {
    for path in links {
        let Ok(meta) = path.symlink_metadata() else {
            continue;
        };
        if meta.file_type().is_symlink() {
            if let Ok(target) = fs::read_link(path)
                && target.starts_with(venv_root)
            {
                let _ = fs::remove_file(path);
            }
        } else if meta.file_type().is_file()
            && let Ok(contents) = fs::read_to_string(path)
        {
            let mut lines = contents.lines();
            lines.next(); // shebang
            if lines.next().is_some_and(|l| l.starts_with(SENTINEL)) {
                let _ = fs::remove_file(path);
            }
        }
    }
}

// -- Per-venv convergence --

/// UI handles for one worker: the worker's own bar plus the shared
/// MultiProgress (used to suspend rendering around inherited-stdio commands).
struct Ui<'a> {
    pb: &'a ProgressBar,
    multi: &'a MultiProgress,
}

#[allow(clippy::too_many_arguments)]
fn converge_one(
    uv: &Path,
    resolved: &ResolvedVirtualEnv,
    locator: &Locator,
    link_dir: &Path,
    state: &Mutex<ManagedState>,
    state_path: &Path,
    sys_version: &str,
    old_links: &[PathBuf],
    ui: &Ui<'_>,
) -> Result<()> {
    let pb = ui.pb;
    let venv_dir = locator.for_name(&resolved.name);

    // Clean up stale links from the previous convergence of this venv.
    remove_links(old_links, &locator.root);

    // Recreate the venv.
    pb.set_message(format!("{}: creating venv", resolved.name));
    if venv_dir.exists() {
        fs::remove_dir_all(&venv_dir)
            .with_context(|| format!("removing existing venv {}", venv_dir.display()))?;
    }

    run_captured(
        Command::new(uv)
            .args(["venv", "--python", &resolved.python, "--quiet"])
            .arg(&venv_dir),
        &resolved.name,
        "uv venv",
    )?;

    // Install packages.
    if !resolved.install.is_empty() || !resolved.requirements.is_empty() {
        pb.set_message(format!("{}: installing packages", resolved.name));

        let venv_python = venv_dir.join("bin/python");
        let mut cmd = Command::new(uv);
        cmd.args(["pip", "install", "--python"])
            .arg(&venv_python)
            .arg("--quiet");
        for package in &resolved.install {
            cmd.arg(package);
        }
        for req in &resolved.requirements {
            cmd.args(["-r", req.as_str()]);
        }
        run_captured(&mut cmd, &resolved.name, "uv pip install")?;
    }

    // Create links. (link_dir itself is created once in apply() before the parallel loop.)
    pb.set_message(format!("{}: linking", resolved.name));

    let mut created_links = Vec::with_capacity(resolved.link.len() + resolved.link_module.len());

    for link in &resolved.link {
        created_links.push(create_symlink(&venv_dir, link, link_dir)?);
    }
    for link in &resolved.link_module {
        created_links.push(write_module_wrapper(&venv_dir, link, link_dir)?);
    }

    // Update state and persist it (before post-commands, so links are
    // tracked even if a post-command fails — and so an interrupted run
    // leaves a record of every venv that successfully reached this point).
    {
        let mut state = state.lock().unwrap();
        state.venvs.insert(
            resolved.name.clone(),
            VenvState {
                config: resolved.clone(),
                sys_version: sys_version.to_string(),
                links: created_links,
            },
        );
        state
            .save(state_path)
            .context("saving managed state after converge")?;
    }

    // Run post-commands. They inherit our stdout/stderr, so suspend the
    // progress bars while each one runs to keep the terminal coherent.
    for command in &resolved.post_commands {
        if command.is_empty() {
            continue;
        }
        pb.set_message(format!("{}: running {}", resolved.name, command[0],));
        let status = ui
            .multi
            .suspend(|| Command::new(&command[0]).args(&command[1..]).status())
            .with_context(|| format!("running post-command: {command:?}"))?;
        if !status.success() {
            bail!("post-command failed for {}: {command:?}", resolved.name,);
        }
    }

    Ok(())
}

/// Run a command, capturing stdout/stderr. On failure, include stderr
/// in the error message (so it doesn't interleave with progress bars
/// during normal operation).
fn run_captured(cmd: &mut Command, venv_name: &str, description: &str) -> Result<()> {
    let output = cmd
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .with_context(|| format!("running {description}"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("{description} failed for {venv_name}:\n{stderr}");
    }
    Ok(())
}

/// Check that a venv's python interpreter is callable.
///
/// `try_exists` follows symlinks, so a broken `bin/python` symlink (e.g.
/// from a deleted Python install) resolves to `Ok(false)`. The system
/// python itself was already validated at the start of `run()` via
/// `resolve_python_versions`, so a resolvable symlink here implies a
/// working interpreter without paying for a subprocess per healthy venv.
fn health_check(venv_dir: &Path) -> bool {
    let python = venv_dir.join("bin/python");
    matches!(python.try_exists(), Ok(true))
}

fn create_symlink(venv_dir: &Path, link: &LinkSpec, link_dir: &Path) -> Result<PathBuf> {
    let source = venv_dir.join("bin").join(&link.source);
    let target = link_dir.join(&link.target);

    if let Ok(meta) = target.symlink_metadata() {
        if meta.file_type().is_symlink() {
            if fs::read_link(&target).ok().as_ref() == Some(&source) {
                return Ok(target);
            }
            // Broken symlink or points elsewhere — only replace if broken.
            if target.exists() {
                bail!(
                    "link target {} already exists \
                     (symlink to something else)",
                    target.display(),
                );
            }
            fs::remove_file(&target)?;
        } else {
            bail!(
                "link target {} already exists (not a symlink)",
                target.display(),
            );
        }
    }

    symlink(&source, &target)
        .with_context(|| format!("symlinking {} -> {}", source.display(), target.display(),))?;

    Ok(target)
}

fn write_module_wrapper(venv_dir: &Path, link: &LinkSpec, link_dir: &Path) -> Result<PathBuf> {
    let python = venv_dir.join("bin/python");
    let python_str = python
        .to_str()
        .with_context(|| format!("python path is not valid UTF-8: {}", python.display()))?;
    let target = link_dir.join(&link.target);

    // Refuse to overwrite files we didn't generate.
    if target.exists() {
        let contents = fs::read_to_string(&target).unwrap_or_default();
        let mut lines = contents.lines();
        lines.next(); // skip shebang
        if !lines.next().is_some_and(|l| l.starts_with(SENTINEL)) {
            bail!(
                "link target {} already exists (not a venvs wrapper)",
                target.display(),
            );
        }
    }

    let wrapper = format!(
        "\
#!{python_str}
{SENTINEL}
# Don't modify this file, it may be replaced when re-converging.
import os
import sys
# No runpy.run_module because of https://bugs.python.org/issue37941 ...
argv = [sys.executable, \"-m\", \"{module}\"] + sys.argv[1:]
os.execvp(argv[0], argv)
",
        module = link.source,
    );

    fs::write(&target, &wrapper)
        .with_context(|| format!("writing module wrapper {}", target.display()))?;

    let mut perms = fs::metadata(&target)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&target, perms)?;

    Ok(target)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_venv(name: &str) -> ResolvedVirtualEnv {
        ResolvedVirtualEnv {
            name: name.to_string(),
            python: "python3".to_string(),
            install: vec![],
            requirements: vec![],
            link: vec![],
            link_module: vec![],
            post_commands: vec![],
        }
    }

    fn sample_state(name: &str, sys_version: &str) -> VenvState {
        VenvState {
            config: sample_venv(name),
            sys_version: sys_version.to_string(),
            links: vec![],
        }
    }

    #[test]
    fn describe_changes_empty_when_unchanged() {
        let existing = sample_state("foo", "Python 3.12.0");
        let resolved = sample_venv("foo");
        assert!(describe_changes(&existing, &resolved, "Python 3.12.0").is_empty());
    }

    #[test]
    fn describe_changes_reports_python_version() {
        let existing = sample_state("foo", "Python 3.11.0");
        let resolved = sample_venv("foo");
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(reasons.len(), 1);
        assert!(reasons[0].contains("3.11.0"));
        assert!(reasons[0].contains("3.12.0"));
    }

    #[test]
    fn describe_changes_reports_install_diff() {
        let existing = sample_state("foo", "Python 3.12.0");
        let mut resolved = sample_venv("foo");
        resolved.install.push("flask".into());
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(reasons, vec!["install: +flask".to_string()]);
    }

    #[test]
    fn describe_changes_reports_install_add_and_remove() {
        let mut existing = sample_state("foo", "Python 3.12.0");
        existing.config.install = vec!["django".into(), "redis".into()];
        let mut resolved = sample_venv("foo");
        resolved.install = vec!["redis".into(), "flask".into()];
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(reasons, vec!["install: +flask -django".to_string()]);
    }

    #[test]
    fn describe_changes_reports_link_diff() {
        let mut existing = sample_state("foo", "Python 3.12.0");
        existing.config.link = vec![LinkSpec {
            source: "old".into(),
            target: "old".into(),
        }];
        let mut resolved = sample_venv("foo");
        resolved.link = vec![LinkSpec {
            source: "new".into(),
            target: "alias".into(),
        }];
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(reasons, vec!["links: +new:alias -old".to_string()]);
    }

    #[test]
    fn describe_changes_reports_reorder() {
        let mut existing = sample_state("foo", "Python 3.12.0");
        existing.config.install = vec!["a".into(), "b".into()];
        let mut resolved = sample_venv("foo");
        resolved.install = vec!["b".into(), "a".into()];
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(reasons, vec!["install reordered".to_string()]);
    }

    #[test]
    fn describe_changes_reports_python_spec() {
        let existing = sample_state("foo", "Python 3.12.0");
        let mut resolved = sample_venv("foo");
        resolved.python = "python3.13".into();
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(
            reasons,
            vec!["python spec: python3 -> python3.13".to_string()]
        );
    }

    #[test]
    fn describe_changes_reports_link_module_diff() {
        let existing = sample_state("foo", "Python 3.12.0");
        let mut resolved = sample_venv("foo");
        resolved.link_module = vec![LinkSpec {
            source: "ipython".into(),
            target: "ipy".into(),
        }];
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(reasons, vec!["link-modules: +ipython:ipy".to_string()]);
    }

    #[test]
    fn describe_changes_reports_post_commands_change() {
        let existing = sample_state("foo", "Python 3.12.0");
        let mut resolved = sample_venv("foo");
        resolved.post_commands = vec![vec!["echo".into(), "hi".into()]];
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(reasons, vec!["post-commands changed".to_string()]);
    }

    #[test]
    fn diff_strings_handles_duplicate_removal() {
        let old = vec!["a".into(), "a".into(), "b".into()];
        let new = vec!["a".into(), "b".into()];
        assert_eq!(diff_strings("install", &old, &new), "install: -a");
    }

    #[test]
    fn diff_strings_handles_duplicate_addition() {
        let old = vec!["a".into()];
        let new = vec!["a".into(), "a".into(), "a".into()];
        assert_eq!(diff_strings("install", &old, &new), "install: +a +a");
    }

    #[test]
    fn diff_strings_treats_equal_multisets_as_reordered() {
        let old = vec!["a".into(), "b".into(), "a".into()];
        let new = vec!["b".into(), "a".into(), "a".into()];
        assert_eq!(diff_strings("install", &old, &new), "install reordered");
    }

    #[test]
    fn describe_changes_reports_multiple_diffs() {
        let existing = sample_state("foo", "Python 3.11.0");
        let mut resolved = sample_venv("foo");
        resolved.python = "python3.12".into();
        resolved.install.push("flask".into());
        let reasons = describe_changes(&existing, &resolved, "Python 3.12.0");
        assert_eq!(reasons.len(), 3);
    }

    fn config_with(venvs: &[&str]) -> Config {
        let mut s = String::new();
        for name in venvs {
            s.push_str(&format!("[virtualenv.{name}]\n"));
        }
        Config::parse(&s).unwrap()
    }

    fn versions(specs: &[(&str, &str)]) -> HashMap<String, String> {
        specs
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
            .collect()
    }

    /// Build a plan against the given locator/state with sensible defaults
    /// for tests (no name filter, link_dir = tempdir parent, single python
    /// version mapping).
    fn plan_for(
        config: &Config,
        state: &ManagedState,
        locator: &Locator,
        link_dir: &Path,
        names: &[String],
    ) -> Result<Plan> {
        build_plan(
            config,
            state,
            &versions(&[("python3", "Python 3.12.0")]),
            names,
            locator,
            link_dir,
        )
    }

    #[test]
    fn build_plan_creates_when_state_empty() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        let config = config_with(&["foo"]);
        let state = ManagedState::default();
        let plan = plan_for(&config, &state, &locator, dir.path(), &[]).unwrap();
        assert!(plan.orphans.is_empty());
        assert!(matches!(
            plan.items.as_slice(),
            [Item {
                verdict: Verdict::Create,
                ..
            }],
        ));
    }

    #[test]
    fn build_plan_skips_when_unchanged_and_healthy() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        // Make a healthy venv on disk.
        let venv_dir = locator.for_name("foo");
        fs::create_dir_all(venv_dir.join("bin")).unwrap();
        fs::write(venv_dir.join("bin/python"), b"").unwrap();

        let config = config_with(&["foo"]);
        let mut state = ManagedState::default();
        state
            .venvs
            .insert("foo".into(), sample_state("foo", "Python 3.12.0"));

        let plan = plan_for(&config, &state, &locator, dir.path(), &[]).unwrap();
        assert!(matches!(
            plan.items.as_slice(),
            [Item { verdict: Verdict::Skip, resolved, .. }] if resolved.name == "foo"
        ));
    }

    #[test]
    fn build_plan_updates_when_unhealthy_even_without_config_change() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        // No venv on disk -> unhealthy.

        let config = config_with(&["foo"]);
        let mut state = ManagedState::default();
        state
            .venvs
            .insert("foo".into(), sample_state("foo", "Python 3.12.0"));

        let plan = plan_for(&config, &state, &locator, dir.path(), &[]).unwrap();
        match plan.items.as_slice() {
            [
                Item {
                    verdict: Verdict::Update { reasons, .. },
                    ..
                },
            ] => {
                assert_eq!(reasons, &vec!["venv missing or broken".to_string()]);
            }
            other => panic!("expected single Update item, got {other:?}"),
        }
    }

    #[test]
    fn build_plan_detects_orphans() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        let config = config_with(&["foo"]);
        let mut state = ManagedState::default();
        state.venvs.insert(
            "stale".into(),
            VenvState {
                config: sample_venv("stale"),
                sys_version: "Python 3.12.0".to_string(),
                links: vec![PathBuf::from("/some/link")],
            },
        );
        let plan = plan_for(&config, &state, &locator, dir.path(), &[]).unwrap();
        assert_eq!(plan.orphans.len(), 1);
        assert_eq!(plan.orphans[0].name, "stale");
        assert_eq!(plan.orphans[0].links.len(), 1);
    }

    #[test]
    fn build_plan_filters_by_names() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        let config = config_with(&["a", "b", "c"]);
        let state = ManagedState::default();
        let plan = plan_for(&config, &state, &locator, dir.path(), &["b".to_string()]).unwrap();
        assert_eq!(plan.items.len(), 1);
        assert!(matches!(plan.items[0].verdict, Verdict::Create));
        assert_eq!(plan.items[0].resolved.name, "b");
    }

    #[test]
    fn build_plan_rejects_unknown_filter_names() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        let config = config_with(&["a", "b"]);
        let state = ManagedState::default();
        let err = plan_for(
            &config,
            &state,
            &locator,
            dir.path(),
            &["a".to_string(), "typo".to_string(), "another".to_string()],
        )
        .unwrap_err();
        let msg = format!("{err:#}");
        assert!(msg.contains("typo"), "error should name the typo: {msg}");
        assert!(
            msg.contains("another"),
            "error should name all unknowns: {msg}"
        );
        assert!(
            !msg.contains("'a'"),
            "error should not mention valid names: {msg}"
        );
    }

    #[test]
    fn plan_has_changes_reflects_orphans_and_non_skips() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };

        // No config, no state -> empty plan, no changes.
        let empty = plan_for(
            &config_with(&[]),
            &ManagedState::default(),
            &locator,
            dir.path(),
            &[],
        )
        .unwrap();
        assert!(!empty.has_changes());

        // Config has a venv that's not in state -> Create -> changes.
        let creating = plan_for(
            &config_with(&["foo"]),
            &ManagedState::default(),
            &locator,
            dir.path(),
            &[],
        )
        .unwrap();
        assert!(creating.has_changes());

        // Healthy unchanged venv -> Skip -> no changes.
        let venv_dir = locator.for_name("foo");
        fs::create_dir_all(venv_dir.join("bin")).unwrap();
        fs::write(venv_dir.join("bin/python"), b"").unwrap();
        let mut state = ManagedState::default();
        state
            .venvs
            .insert("foo".into(), sample_state("foo", "Python 3.12.0"));
        let skipping = plan_for(&config_with(&["foo"]), &state, &locator, dir.path(), &[]).unwrap();
        assert!(!skipping.has_changes());

        // Orphan in state alone is enough to count as changes.
        let mut orphan_state = ManagedState::default();
        orphan_state
            .venvs
            .insert("ghost".into(), sample_state("ghost", "Python 3.12.0"));
        let with_orphan =
            plan_for(&config_with(&[]), &orphan_state, &locator, dir.path(), &[]).unwrap();
        assert!(with_orphan.has_changes());
    }

    fn render(plan: &Plan, link_dir: &Path) -> String {
        let mut buf = Vec::new();
        print_plan(plan, link_dir, &mut buf).unwrap();
        String::from_utf8(buf).unwrap()
    }

    #[test]
    fn print_plan_says_up_to_date_when_no_changes() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        let plan = plan_for(
            &config_with(&[]),
            &ManagedState::default(),
            &locator,
            dir.path(),
            &[],
        )
        .unwrap();
        let out = render(&plan, dir.path());
        assert_eq!(out.trim(), "Already up to date — no changes needed.");
    }

    #[test]
    fn print_plan_omits_skip_lines_when_changes_pending() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        // Make foo healthy and unchanged so it'll be a Skip.
        let foo_dir = locator.for_name("foo");
        fs::create_dir_all(foo_dir.join("bin")).unwrap();
        fs::write(foo_dir.join("bin/python"), b"").unwrap();

        let mut state = ManagedState::default();
        state
            .venvs
            .insert("foo".into(), sample_state("foo", "Python 3.12.0"));

        let plan = plan_for(
            &config_with(&["foo", "bar"]),
            &state,
            &locator,
            dir.path(),
            &[],
        )
        .unwrap();
        let out = render(&plan, dir.path());
        assert!(
            !out.contains("foo"),
            "skipped venv 'foo' should not appear in output: {out}",
        );
        assert!(
            out.contains("Would create: bar"),
            "create line for 'bar' should be shown: {out}",
        );
    }

    #[test]
    fn dry_run_exit_code_2_for_changes_0_for_no_op() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };

        let no_op = plan_for(
            &config_with(&[]),
            &ManagedState::default(),
            &locator,
            dir.path(),
            &[],
        )
        .unwrap();
        assert_eq!(dry_run_exit_code(&no_op), 0);

        let creating = plan_for(
            &config_with(&["foo"]),
            &ManagedState::default(),
            &locator,
            dir.path(),
            &[],
        )
        .unwrap();
        assert_eq!(dry_run_exit_code(&creating), 2);
    }

    #[test]
    fn print_plan_renders_orphans_and_updates() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().to_path_buf(),
        };
        let mut state = ManagedState::default();
        // Add an orphan with one link.
        state.venvs.insert(
            "ghost".into(),
            VenvState {
                config: sample_venv("ghost"),
                sys_version: "Python 3.12.0".to_string(),
                links: vec![PathBuf::from("/some/link")],
            },
        );
        // Add foo as needing update (config differs from state).
        let mut existing_foo = sample_state("foo", "Python 3.12.0");
        existing_foo.config.install = vec!["old".into()];
        state.venvs.insert("foo".into(), existing_foo);
        // foo on disk so it's healthy (forces config-driven update reason).
        let foo_dir = locator.for_name("foo");
        fs::create_dir_all(foo_dir.join("bin")).unwrap();
        fs::write(foo_dir.join("bin/python"), b"").unwrap();

        let mut s = String::from("[virtualenv.foo]\ninstall = [\"new\"]\n");
        s.push_str("[virtualenv.bar]\n");
        let config = Config::parse(&s).unwrap();

        let plan = plan_for(&config, &state, &locator, dir.path(), &[]).unwrap();
        let out = render(&plan, dir.path());
        assert!(out.contains("Would remove orphan: ghost (1 link(s))"));
        assert!(out.contains("Would update: foo (install: +new -old)"));
        assert!(out.contains("Would create: bar"));
    }

    #[test]
    fn build_plan_records_link_dir_existence() {
        let dir = tempfile::tempdir().unwrap();
        let locator = Locator {
            root: dir.path().join("venvs"),
        };
        let config = config_with(&[]);
        let state = ManagedState::default();

        let existing = dir.path().join("existing");
        fs::create_dir(&existing).unwrap();
        let absent = dir.path().join("absent");

        assert!(
            plan_for(&config, &state, &locator, &existing, &[])
                .unwrap()
                .link_dir_exists,
        );
        assert!(
            !plan_for(&config, &state, &locator, &absent, &[])
                .unwrap()
                .link_dir_exists,
        );
    }

    #[test]
    fn health_check_nonexistent_dir() {
        assert!(!health_check(Path::new("/nonexistent/venv")));
    }

    #[test]
    fn acquire_lock_blocks_second_acquire() {
        let dir = tempfile::tempdir().unwrap();
        let _first = acquire_lock(dir.path()).expect("first lock should succeed");
        let err = acquire_lock(dir.path()).expect_err("second lock should fail");
        assert!(
            err.to_string()
                .contains("another venvs converge is running"),
            "unexpected error: {err}",
        );
    }

    #[test]
    fn acquire_lock_releases_on_drop() {
        let dir = tempfile::tempdir().unwrap();
        {
            let _first = acquire_lock(dir.path()).expect("first lock should succeed");
        }
        // Now the lock is dropped — acquiring it again should succeed.
        acquire_lock(dir.path()).expect("lock should be re-acquirable after drop");
    }

    #[test]
    fn health_check_healthy_venv() {
        let dir = tempfile::tempdir().unwrap();
        let bin = dir.path().join("bin");
        fs::create_dir_all(&bin).unwrap();
        fs::write(bin.join("python"), b"").unwrap();
        assert!(health_check(dir.path()));
    }

    #[test]
    fn health_check_broken_symlink() {
        let dir = tempfile::tempdir().unwrap();
        let bin = dir.path().join("bin");
        fs::create_dir_all(&bin).unwrap();
        symlink("/definitely/does/not/exist", bin.join("python")).unwrap();
        assert!(!health_check(dir.path()));
    }

    #[test]
    fn create_symlink_new() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        let result = create_symlink(&venv_dir, &spec, &link_dir).unwrap();
        assert_eq!(result, link_dir.join("mytool"));
        assert_eq!(
            fs::read_link(link_dir.join("mytool")).unwrap(),
            bin_dir.join("mytool"),
        );
    }

    #[test]
    fn create_symlink_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        create_symlink(&venv_dir, &spec, &link_dir).unwrap();
        // Second call should succeed (same target).
        create_symlink(&venv_dir, &spec, &link_dir).unwrap();
    }

    #[test]
    fn create_symlink_replaces_broken() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        // Create a broken symlink.
        symlink("/nonexistent/target", link_dir.join("mytool")).unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        create_symlink(&venv_dir, &spec, &link_dir).unwrap();
        assert_eq!(
            fs::read_link(link_dir.join("mytool")).unwrap(),
            bin_dir.join("mytool"),
        );
    }

    #[test]
    fn create_symlink_refuses_existing_file() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        // Create a real file at the target.
        fs::write(link_dir.join("mytool"), "something").unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        assert!(create_symlink(&venv_dir, &spec, &link_dir).is_err());
    }

    #[test]
    fn create_symlink_refuses_existing_symlink_to_other_target() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();
        fs::write(bin_dir.join("mytool"), "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        // Create a working symlink to a different file.
        let other_file = dir.path().join("other");
        fs::write(&other_file, "other").unwrap();
        symlink(&other_file, link_dir.join("mytool")).unwrap();

        let spec = LinkSpec {
            source: "mytool".into(),
            target: "mytool".into(),
        };

        assert!(create_symlink(&venv_dir, &spec, &link_dir).is_err());
    }

    #[test]
    fn write_module_wrapper_creates_executable() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        let spec = LinkSpec {
            source: "mymodule".into(),
            target: "mymod".into(),
        };

        let result = write_module_wrapper(&venv_dir, &spec, &link_dir).unwrap();
        assert_eq!(result, link_dir.join("mymod"));

        let contents = fs::read_to_string(&result).unwrap();
        assert!(contents.starts_with("#!"));
        assert!(contents.contains(SENTINEL));
        assert!(contents.contains("\"mymodule\""));

        let mode = fs::metadata(&result).unwrap().permissions().mode();
        assert_ne!(mode & 0o111, 0, "wrapper should be executable");
    }

    #[test]
    fn write_module_wrapper_replaces_own_wrappers() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        let spec = LinkSpec {
            source: "mymodule".into(),
            target: "mymod".into(),
        };

        write_module_wrapper(&venv_dir, &spec, &link_dir).unwrap();
        // Second call should succeed (replaces its own wrapper).
        write_module_wrapper(&venv_dir, &spec, &link_dir).unwrap();
    }

    #[test]
    fn remove_links_removes_symlink_into_venv_root() {
        let dir = tempfile::tempdir().unwrap();
        let venv_root = dir.path().join("venvs");
        let bin = venv_root.join("myenv/bin");
        fs::create_dir_all(&bin).unwrap();
        let source = bin.join("tool");
        fs::write(&source, "#!/bin/sh\n").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();
        let link = link_dir.join("tool");
        symlink(&source, &link).unwrap();

        remove_links(std::slice::from_ref(&link), &venv_root);
        assert!(!link.exists() && link.symlink_metadata().is_err());
    }

    #[test]
    fn remove_links_skips_symlink_outside_venv_root() {
        let dir = tempfile::tempdir().unwrap();
        let venv_root = dir.path().join("venvs");
        fs::create_dir_all(&venv_root).unwrap();

        let outside = dir.path().join("important_file");
        fs::write(&outside, "do not delete").unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();
        let link = link_dir.join("evil");
        symlink(&outside, &link).unwrap();

        remove_links(std::slice::from_ref(&link), &venv_root);

        // The symlink is left in place because its target isn't under venv_root.
        assert!(link.symlink_metadata().is_ok());
        assert!(outside.exists());
    }

    #[test]
    fn remove_links_skips_arbitrary_regular_file() {
        // A poisoned state record like `links = ["/etc/passwd"]` must not
        // cause arbitrary file deletion.
        let dir = tempfile::tempdir().unwrap();
        let venv_root = dir.path().join("venvs");
        fs::create_dir_all(&venv_root).unwrap();

        let unrelated = dir.path().join("unrelated.txt");
        fs::write(&unrelated, "not a venvs wrapper").unwrap();

        remove_links(std::slice::from_ref(&unrelated), &venv_root);
        assert!(unrelated.exists(), "unrelated file should not be removed");
    }

    #[test]
    fn remove_links_removes_wrapper_with_sentinel() {
        let dir = tempfile::tempdir().unwrap();
        let venv_root = dir.path().join("venvs");
        fs::create_dir_all(&venv_root).unwrap();

        let wrapper = dir.path().join("links/wrapper");
        fs::create_dir_all(wrapper.parent().unwrap()).unwrap();
        fs::write(&wrapper, format!("#!/usr/bin/python\n{SENTINEL}\n# rest\n")).unwrap();

        remove_links(std::slice::from_ref(&wrapper), &venv_root);
        assert!(!wrapper.exists());
    }

    #[test]
    fn write_module_wrapper_refuses_foreign_files() {
        let dir = tempfile::tempdir().unwrap();
        let venv_dir = dir.path().join("myenv");
        let bin_dir = venv_dir.join("bin");
        fs::create_dir_all(&bin_dir).unwrap();

        let link_dir = dir.path().join("links");
        fs::create_dir_all(&link_dir).unwrap();

        // Create a file that isn't a venvs wrapper.
        fs::write(link_dir.join("mymod"), "something else\n").unwrap();

        let spec = LinkSpec {
            source: "mymodule".into(),
            target: "mymod".into(),
        };

        assert!(write_module_wrapper(&venv_dir, &spec, &link_dir).is_err());
    }
}
